version: "3.9"

services:
  trading_bot:
    build: .
    container_name: trading_service
    restart: always
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
