version: "3.3"

services:
  trading_bot:
    build: .
    container_name: trading_webhook_service
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - CATEGORY=${CATEGORY}
      - STOP_LOSS_PERCENT=${STOP_LOSS_PERCENT}

