[tool.poetry]
name = "bybit-trading-bot"
version = "0.1.0"
description = ""
authors = ["Krushovice <kickstar69@yandex.ru>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.1"
pybit = "^5.8.0"
redis = "^5.2.1"
fastapi = {extras = ["standard"], version = "^0.115.12"}
pydantic = "^2.11.1"
slowapi = "^0.1.9"
aiogram = "^3.20.0.post0"
pydantic-settings = "^2.9.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pre-commit = "^4.2.0"
black = "^25.1.0"
ruff = "^0.11.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
